### ISSUE TITLE
Mod fails to load at creating Diesel Generators Stage

### ISSUE THREAD

**Issue by Nielwulf** [Wehmeyer100/CoI.Mod.Better#10]
Mod fails to load either at the stage of creating diesel generators or directly after. Complaints of Generator creating more electricity than consuming mechanical power.

Log is attached.
[22-06-09_09-47-45_6126.log](https://github.com/Wehmeyer100/CoI.Mod.Better/files/8871507/22-06-09_09-47-45_6126.log)

**Comment by Nielwulf** [comment]
Looked to be a conflict with CheatMenu, closing due to lack of troubleshooting on my part

**Comment by Wehmeyer100** [comment]
This error ist a Assert error and cannot try catch. This is okey.
