### ISSUE TITLE
coulnd't initialize a game

### ISSUE THREAD

**Issue by WollysWolfPack** [Wehmeyer100/CoI.Mod.Better#17]
[22-06-10_18-20-10_1110.log](https://github.com/Wehmeyer100/CoI.Mod.Better/files/8880525/22-06-10_18-20-10_1110.log)

couldn't initializea game, neither savegame nor a new game, switched back to previous release works at the moment

**Comment by Wehmeyer100** [comment]
Hey, 

the missing dll files is added, sry is my bad. The hotfix is worked.

Sry.
Luxgor
