### ISSUE TITLE
hola problemas con game 0.4.12 c

### ISSUE THREAD

**Issue by emdas20** [Wehmeyer100/CoI.Mod.Better#32]
hola gracias por responder,  estos son los errores que me parecen con game 0.4.12 c y la version mod 0.196 subida hace 8 horas
la primera imagen es de una partida guardada con el juego 0.4.11 y mod 30 Jul 2022 que se abre desde el 0.4.12 c
![errorjuegoguardado](https://user-images.githubusercontent.com/111129732/193098487-adaad37a-8138-4de9-b03b-370025b6d370.jpg)

segunda imagen es una nueva partida desde game 0.4.12 c y la version mod 0.196
![errorpartidanueva](https://user-images.githubusercontent.com/111129732/193098529-2f73e79d-27ad-428a-9210-1e02609698ab.jpg)
![errorjuegoguardado1](https://user-images.githubusercontent.com/111129732/193102391-a84da4eb-d885-45f3-912c-b47f6e08da91.jpg)
![errorpartidanueva1](https://user-images.githubusercontent.com/111129732/193102400-6d1cd69a-eb4e-478d-a9b5-508ae004a18b.jpg)
luego probe con las 3 actualizaciones desde hace 12 horas pero no andan

**Comment by Wehmeyer100** [comment]
Updated to newstes game version

**Comment by emdas20** [comment]
probare con el 0.4.12E gracias

**Comment by emdas20** [comment]
gracias si anda el mod con   0.4.12E solo que me sale las partidas guardas como dañadas pero hay que comenzar de nuevo

**Comment by emdas20** [comment]
algunas imágenes eran erróneas, las dos ultimas del primer mensaje son las correctas
