### ISSUE TITLE
Could not load file or assembly Col.Mod.Better.Shared

### ISSUE THREAD

**Issue by adiamaq** [Wehmeyer100/CoI.Mod.Better#34]
Hello, I'm not able to load this mod in the latest version of the game. Folder name checks, all vanilla, integrity checked. Log attached.
[22-10-16_18-06-36_9583.log](https://github.com/Wehmeyer100/CoI.Mod.Better/files/9795148/22-10-16_18-06-36_9583.log)

**Comment by Wehmeyer100** [comment]
You has not copy "Col.Mod.Better.Shared.dll" in mod root directory. Add the file from last realease and is working.

This mod hasnt assets.

**Comment by Wehmeyer100** [comment]
Log please.

**Comment by askewdread** [comment]
i get the same error mentioned in the beginning, the .shared.dll file does exist in the coi.mod.better folder as downloaded in the release
[22-10-27_06-04-00_3357.log](https://github.com/Wehmeyer100/CoI.Mod.Better/files/9872131/22-10-27_06-04-00_3357.log)

**Comment by Cengro** [comment]
I am getting the same error as well with new save.
