### ISSUE TITLE
Minor bug in the config, Void Producer can't be 'true' unless the Void Crusher is 'true'

### ISSUE THREAD

**Issue by zytukin** [Wehmeyer100/CoI.Mod.Better#38]
Setting both the VoidCrusher and VoidProducer to False or True in the config and the game is fine.
Set VoidCrusher to 'true' and VoidProducer to 'false', and and the game is fine. 
Set VoidCrusher to 'false' and VoidProducer to 'true', and you can't start a new game, it will fail and kick you back to the main menu.

**Comment by Wehmeyer100** [comment]
Systems can be changed only for new games. It is always possible to activate a system, but it is not possible to deactivate it. This is not supported by the game. 

In other words, if something new is added, it cannot be removed in the savegame. However, this only applies to buildings, resources, research, ethics for captain's office or similar.

**Comment by zytukin** [comment]
"Systems can be changed only for new games"

And that is when the bug happens, lol.

"Set VoidCrusher to 'false' and VoidProducer to 'true', **and you can't start a new game,** it will fail and kick you back to the main memu"
