### ISSUE TITLE
Latest release does not load on updated 0.5.0 (Update 1)

### ISSUE THREAD

**Issue by JonJoyce** [Wehmeyer100/CoI.Mod.Better#40]
![image](https://github.com/Wehmeyer100/CoI.Mod.Better/assets/448438/351833df-430c-4fcb-8b47-e4f7ada47745)

Mod does not load, no errors in logs that i've seen.
Needs an update for 0.5.0 when you get a chance please :)

**Comment by Wehmeyer100** [comment]
Beta Patch is live.

**Comment by Wehmeyer100** [comment]
Mafi Games change saves and mods directories:

Saves: C:\Users#PC_USERNAME#\AppData\Roaming\Captain of Industry\Saves\
Mods: C:\Users#PC_USERNAME#\AppData\Roaming\Captain of Industry\Mods\
