### ISSUE TITLE
.csproj file in source code uses absolute path for dependencies

### ISSUE THREAD

**Issue by Nielwulf** [Wehmeyer100/CoI.Mod.Better#9]
When initially loading the source code, it is unable to find the Mafi dependencies due to the .csproj using absolute paths to point to the CoI .dlls.

The Mafi mod repo has you add your CoI install directory as an env variable. It probably means making changes to your own environment, but I would request that you update the .csproj file paths to match what is listed in the Mafi mod repo. They use, $COI_ROOT as their env variable. The end result looks like below in the .csproj file

<Reference Include="Mafi">
      <HintPath>$(COI_ROOT)\Captain of Industry_Data\Managed\Mafi.dll</HintPath>
</Reference>

**Comment by Nielwulf** [comment]
Created pull request, https://github.com/Wehmeyer100/CoI.Mod.Better/pull/11

**Comment by Wehmeyer100** [comment]
Thx, for your work.
